### ISSUE TITLE
Links Demo

### ISSUE THREAD

**Issue by paichato** [rafinhaa/ControlMEI#1]
E ai rafinha?! Projectos interessantes que tu tens. Podias colocar os links de demostrancao para que possamos ver a aplicacao em funcionamento?

**Comment by rafinhaa** [comment]
Olá! obrigado por comentar, você tem alguma documentação para indicar de como fazer?

**Comment by paichato** [comment]
https://www.youtube.com/watch?v=S2tIDoXmKbo

**Comment by rafinhaa** [comment]
Obrigado, será adicionado conforme o tempo.
